describe('Register Test - Parabank', () => {

    const randomUser = `user_${Date.now()}`;
    const realPassword = '1234567';
    
    it('1.Register with valid data', () => {
        cy.visit('/')
        cy.get('#loginPanel').find('p').contains('Register').click()
        cy.get('input[name="customer.firstName"]').type('test123')
        cy.get('input[name="customer.lastName"]').type('test456')
        cy.get('input[name="customer.address.street"]').type('aaaaaaa')
        cy.get('input[name="customer.address.city"]').type('newyork')
        cy.get('input[name="customer.address.state"]').type('USA')
        cy.get('input[name="customer.address.zipCode"]').type('123456')
        cy.get('input[name="customer.phoneNumber"]').type('1234567890')
        cy.get('input[name="customer.ssn"]').type('12345678910')
        cy.get('input[name="customer.username"]').type('fortest1')
        cy.get('input[name="customer.password"]').type(realPassword)
        cy.get('input[name="repeatedPassword"]').type(realPassword)
        cy.get('input[value="Register"]').click()
        cy.contains('Your account was created successfully').should('be.visible')
       
    })

    it('2.Leave required field empty (First Name)', () => {
        cy.visit('/')
        cy.get('#loginPanel').find('p').contains('Register').click()
        // cy.get('input[name="customer.firstName"]').type('test123')
        cy.get('input[name="customer.lastName"]').type('test456')
        cy.get('input[name="customer.address.street"]').type('aaaaaaa')
        cy.get('input[name="customer.address.city"]').type('newyork')
        cy.get('input[name="customer.address.state"]').type('USA')
        cy.get('input[name="customer.address.zipCode"]').type('123456')
        cy.get('input[name="customer.phoneNumber"]').type('1234567890')
        cy.get('input[name="customer.ssn"]').type('12345678910')
        cy.get('input[name="customer.username"]').type(randomUser)
        cy.get('input[name="customer.password"]').type(realPassword)
        cy.get('input[name="repeatedPassword"]').type(realPassword)
        cy.get('input[value="Register"]').click()
        cy.contains('First name is required.').should('be.visible')
    })

    it('3.Leave multiple required fields empty', () => {
        cy.visit('/')
        cy.get('#loginPanel').find('p').contains('Register').click()
        // cy.get('input[name="customer.firstName"]').type('test123')
        // cy.get('input[name="customer.lastName"]').type('test456')
        cy.get('input[name="customer.address.street"]').type('aaaaaaa')
        cy.get('input[name="customer.address.city"]').type('newyork')
        cy.get('input[name="customer.address.state"]').type('USA')
        cy.get('input[name="customer.address.zipCode"]').type('123456')
        cy.get('input[name="customer.phoneNumber"]').type('1234567890')
        cy.get('input[name="customer.ssn"]').type('12345678910')
        cy.get('input[name="customer.username"]').type(randomUser)
        // cy.get('input[name="customer.password"]').type('1234567')
        cy.get('input[name="repeatedPassword"]').type(realPassword)
        cy.get('input[value="Register"]').click()
        cy.contains('First name is required.').should('be.visible')
        cy.contains('Last name is required.').should('be.visible')
        cy.contains('Password is required.').should('be.visible')
    })

    it('4.Password and Confirm Password mismatch', () => {
        cy.visit('/')
        cy.get('#loginPanel').find('p').contains('Register').click()
        cy.get('input[name="customer.firstName"]').type('test123')
        cy.get('input[name="customer.lastName"]').type('test456')
        cy.get('input[name="customer.address.street"]').type('aaaaaaa')
        cy.get('input[name="customer.address.city"]').type('newyork')
        cy.get('input[name="customer.address.state"]').type('USA')
        cy.get('input[name="customer.address.zipCode"]').type('123456')
        cy.get('input[name="customer.phoneNumber"]').type('1234567890')
        cy.get('input[name="customer.ssn"]').type('12345678910')
        cy.get('input[name="customer.username"]').type(randomUser)
        cy.get('input[name="customer.password"]').type(realPassword) 
        cy.get('input[name="repeatedPassword"]').type('1234568') // enter password and confirm are not the same
        cy.get('input[value="Register"]').click()
        cy.contains('Passwords did not match.').should('be.visible')
    })

    it('5.Username already exists', () => {
        cy.visit('/')
        cy.get('#loginPanel').find('p').contains('Register').click()
        cy.get('input[name="customer.firstName"]').type('test123') 
        cy.get('input[name="customer.lastName"]').type('test456')
        cy.get('input[name="customer.address.street"]').type('aaaaaaa')
        cy.get('input[name="customer.address.city"]').type('newyork')
        cy.get('input[name="customer.address.state"]').type('USA')
        cy.get('input[name="customer.address.zipCode"]').type('123456')
        cy.get('input[name="customer.phoneNumber"]').type('1234567890')
        cy.get('input[name="customer.ssn"]').type('12345678910')
        cy.get('input[name="customer.username"]').type('fortest1') // enter a username you have already used
        cy.get('input[name="customer.password"]').type(realPassword)
        cy.get('input[name="repeatedPassword"]').type(realPassword)
        cy.get('input[value="Register"]').click()
        cy.contains('This username already exists.').should('be.visible')
    })

    it('6.Zip Code with letters', () => {
        cy.visit('/')
        cy.get('#loginPanel').find('p').contains('Register').click()
        cy.get('input[name="customer.firstName"]').type('test123') 
        cy.get('input[name="customer.lastName"]').type('test456')
        cy.get('input[name="customer.address.street"]').type('aaaaaaa')
        cy.get('input[name="customer.address.city"]').type('newyork')
        cy.get('input[name="customer.address.state"]').type('USA')
        cy.get('input[name="customer.address.zipCode"]').type('abcde') // enter the Zip Code as letters
        cy.get('input[name="customer.phoneNumber"]').type('1234567890')
        cy.get('input[name="customer.ssn"]').type('12345678910')
        cy.get('input[name="customer.username"]').type(randomUser) 
        cy.get('input[name="customer.password"]').type(realPassword)
        cy.get('input[name="repeatedPassword"]').type(realPassword)
        cy.get('input[value="Register"]').click()
        cy.contains('Invalid Zip Code format').should('be.visible')
    })

    it('7.SSN with letters', () => {
        cy.visit('/')
        cy.get('#loginPanel').find('p').contains('Register').click()
        cy.get('input[name="customer.firstName"]').type('test123') 
        cy.get('input[name="customer.lastName"]').type('test456')
        cy.get('input[name="customer.address.street"]').type('aaaaaaa')
        cy.get('input[name="customer.address.city"]').type('newyork')
        cy.get('input[name="customer.address.state"]').type('USA')
        cy.get('input[name="customer.address.zipCode"]').type('123456') 
        cy.get('input[name="customer.phoneNumber"]').type('1234567890')
        cy.get('input[name="customer.ssn"]').type('abcdef') // enter the Zip Code as letters
        cy.get('input[name="customer.username"]').type(randomUser) 
        cy.get('input[name="customer.password"]').type(realPassword)
        cy.get('input[name="repeatedPassword"]').type(realPassword)
        cy.get('input[value="Register"]').click()
        cy.contains('Invalid SSN format').should('be.visible')
    })

    it('8.Leave Phone number (optional)', () => {
        cy.visit('/')
        cy.get('#loginPanel').find('p').contains('Register').click()
        cy.get('input[name="customer.firstName"]').type('test123')
        cy.get('input[name="customer.lastName"]').type('test456')
        cy.get('input[name="customer.address.street"]').type('aaaaaaa')
        cy.get('input[name="customer.address.city"]').type('newyork')
        cy.get('input[name="customer.address.state"]').type('USA')
        cy.get('input[name="customer.address.zipCode"]').type('123456')
        // cy.get('input[name="customer.phoneNumber"]').type('1234567890') // leave phone number 
        cy.get('input[name="customer.ssn"]').type('12345678910')
        cy.get('input[name="customer.username"]').type(randomUser)
        cy.get('input[name="customer.password"]').type(realPassword)
        cy.get('input[name="repeatedPassword"]').type(realPassword)
        cy.get('input[value="Register"]').click()
        cy.contains('Your account was created successfully').should('be.visible')
    })

        it('9.Username with special characters', () => {
        cy.visit('/')
        cy.get('#loginPanel').find('p').contains('Register').click()
        cy.get('input[name="customer.firstName"]').type('test123')
        cy.get('input[name="customer.lastName"]').type('test456')
        cy.get('input[name="customer.address.street"]').type('aaaaaaa')
        cy.get('input[name="customer.address.city"]').type('newyork')
        cy.get('input[name="customer.address.state"]').type('USA')
        cy.get('input[name="customer.address.zipCode"]').type('123456')
        cy.get('input[name="customer.phoneNumber"]').type('1234567890')
        cy.get('input[name="customer.ssn"]').type('12345678910')
        cy.get('input[name="customer.username"]').type('!@#test!!*') // enter the username with special characters
        cy.get('input[name="customer.password"]').type(realPassword)
        cy.get('input[name="repeatedPassword"]').type(realPassword)
        cy.get('input[value="Register"]').click()
        cy.contains("can't use special characters in username").should('be.visible')
    })
})